**Tensors**

In [1]:
import numpy as np
#dimensions
a=np.array(4)
print(a.ndim)

0


In [2]:
a=np.array([4,12,12,31])
print(a.ndim)

1


In [3]:
a=np.array(([4,12,12],[13,13,41]))
print(a.ndim)
#shape
print(a.shape) 
print(a.size) #rows * cols
print(a.itemsize)

2
(2, 3)
6
8


**Basics**

In [4]:
a=np.array([[1,2,34,5,3,243],[1,2,34,5,3,245]])
print(a)

[[  1   2  34   5   3 243]
 [  1   2  34   5   3 245]]


In [5]:
#Get specific element [r,c]
a[1,5]

np.int64(245)

In [6]:
#Get specifc row
a[0,:]

array([  1,   2,  34,   5,   3, 243])

In [7]:
#Get specific col
a[:,1]

array([2, 2])

In [8]:
#Gettting [start:end:stepsize]
a[0,1:6:2]

array([  2,   5, 243])

**3-D example**

In [9]:
arr=np.array([[[1,2,3],[4,5,6]],[[12,23,45],[67,78,89]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 23, 45],
        [67, 78, 89]]])

In [10]:
#say access 6 , work outside out [3d row num , 2d row , 2d col]
arr[0,1,2]


np.int64(6)

**Initializing Different Types of Arrays**


In [11]:
#All 0 matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#All 1 matrix
np.ones((2,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [13]:
#Any other number
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [14]:
barr=np.array([[[1,2,3],[1,32,123]],[[2,5,6],[6,7,2]]])
barr.shape

(2, 2, 3)

In [15]:
#Using existing array to change all elements to 56
np.full_like(barr,56)

array([[[56, 56, 56],
        [56, 56, 56]],

       [[56, 56, 56],
        [56, 56, 56]]])

In [16]:
#Random decimal Numbers between 0 and 1
np.random.rand(4,2)

array([[0.11155024, 0.59983767],
       [0.31934882, 0.68597204],
       [0.43824464, 0.67989697],
       [0.8746519 , 0.1472428 ]])

In [17]:
#Random Integers 4 to 7 , in size 3*3
np.random.randint(4,7,size=(3,3))

array([[4, 6, 6],
       [5, 6, 4],
       [6, 4, 5]], dtype=int32)

In [18]:
#Identity matrix
np.identity(4,dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

**Creating a matrix using these operations**

In [19]:
out=np.ones((5,5),dtype='int32')
out

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [20]:
z=np.zeros((3,3),dtype='int32')
z[1,1]=9
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int32)

In [21]:
out[1:4,1:4]=z
print(out)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Mathematics**

In [22]:
a=np.array([2,4,6],dtype='int32')

In [23]:
a/2

array([1., 2., 3.])

In [24]:
a*3

array([ 6, 12, 18], dtype=int32)

In [25]:
a+2

array([4, 6, 8], dtype=int32)

In [26]:
b=np.array([2,31,21])
a+b

array([ 4, 35, 27])

In [27]:
a**2


array([ 4, 16, 36], dtype=int32)

In [28]:
np.cos(a)

array([-0.41614684, -0.65364362,  0.96017029])

**Linear Algebra**

In [38]:
ar=np.random.randint(7,size=(2,3))
ar

array([[3, 5, 6],
       [4, 4, 1]], dtype=int32)

In [39]:
br=np.random.randint(3,size=(3,2))
br

array([[0, 1],
       [0, 0],
       [0, 2]], dtype=int32)

In [45]:
np.matmul(ar,br)


array([[ 0, 15],
       [ 0,  6]], dtype=int32)

In [48]:
fg=np.random.randint(4,7,size=(3,3))
np.linalg.det(fg)


np.float64(-40.000000000000014)

In [49]:
np.linalg.inv(fg)

array([[-5.00000000e-01, -7.40148683e-17,  5.00000000e-01],
       [ 3.00000000e-01,  3.00000000e-01, -5.00000000e-01],
       [ 3.00000000e-01, -2.00000000e-01,  0.00000000e+00]])